version: "3.8"

networks:
  open:
    external: true

# https://www.zigbee2mqtt.io/guide/getting-started/#installation
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    #docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
    #network_mode: host
    #network_mode: bridge
    networks:
      - open
    env_file:
      - .env
    volumes:
      - "${DATADIR}/mosquitto/config:/mosquitto/config"
      - "${DATADIR}/mosquitto/data:/mosquitto/data"
      - "${DATADIR}/mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto/config/mosquitto-localhost.conf"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  # zigbee2mosquitto
  # admin http://192.168.0.144
  # It bridges events and allows you to control your Zigbee devices via MQTT.
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    networks:
      - open
    env_file:
      - .env
    depends_on:
      mosquitto:
        condition: service_started
    volumes:
      - ${DATADIR}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # http://192.168.0.144
      - 80:8080
    environment:
      # https://www.zigbee2mqtt.io/guide/configuration/
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://mosquitto:1883
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyACM0
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
